os: Visual Studio 2017

platform:
  - x86

branches:
  only:
    - master


environment:
  BASEDIR: c:\mylibs
  ZLIB_IDIR: c:\mylibs\include
  SDL1_IDIR: c:\mylibs\include\SDL
  SDL2_IDIR: c:\mylibs\include\SDL2
  LIBDIR: c:\mylibs\lib


install:
  - git submodule update --init --recursive
  - cmake --version
  - mkdir %ZLIB_IDIR%
  - mkdir %SDL2_IDIR%
  - mkdir %LIBDIR%
  - cd %TEMP%
  # Download zlib
  - appveyor DownloadFile https://github.com/mmatyas/supermariowar/releases/download/v2.0-beta.0/zlib128-dll.zip
  - 7z x zlib128-dll.zip > nul
  - copy include\* %ZLIB_IDIR% > nul
  - copy lib\* %LIBDIR% > nul
  # Download SDL2
  - appveyor DownloadFile https://www.libsdl.org/release/SDL2-devel-2.0.14-VC.zip
  - appveyor DownloadFile https://www.libsdl.org/projects/SDL_image/release/SDL2_image-devel-2.0.5-VC.zip
  - appveyor DownloadFile https://www.libsdl.org/projects/SDL_mixer/release/SDL2_mixer-devel-2.0.4-VC.zip
  # Extract files
  - 7z x SDL2-devel-2.0.14-VC.zip > nul
  - 7z x SDL2_image-devel-2.0.5-VC.zip > nul
  - 7z x SDL2_mixer-devel-2.0.4-VC.zip > nul
  # Set up includes
  - copy SDL2-2.0.14\include\* %SDL2_IDIR% > nul
  - copy SDL2_image-2.0.5\include\* %SDL2_IDIR% > nul
  - copy SDL2_mixer-2.0.4\include\* %SDL2_IDIR% > nul
  # Set up libs
  - copy SDL2-2.0.14\lib\x86\* %LIBDIR% > nul
  - copy SDL2_image-2.0.5\lib\x86\* %LIBDIR% > nul
  - copy SDL2_mixer-2.0.4\lib\x86\* %LIBDIR% > nul

build_script:
  - cd %APPVEYOR_BUILD_FOLDER%
  - cmake
      -DCMAKE_PREFIX_PATH=%BASEDIR%
      -DCMAKE_BUILD_TYPE=Release
      -DUSE_SDL2_LIBS=ON
      -DUSE_PNG_SAVE=ON
      -G "Visual Studio 15 2017" .
  - cmake --build . --config Release

artifacts:
  - path: '*.exe'
