name: Build - Linux

on: [push, pull_request, workflow_dispatch]

jobs:
  linux:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        sdl: [1, 2]
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'recursive'
      - name: Install dependencies
        run: sudo apt-get update -qq && sudo apt-get install -y
          cmake
          g++
          libsdl1.2-dev
          libsdl-image1.2-dev
          libsdl-mixer1.2-dev
          libsdl2-dev
          libsdl2-image-dev
          libsdl2-mixer-dev
          libegl1-mesa-dev
          libgles2-mesa-dev
          ninja-build
      - name: Version checks
        run: |
          sdl-config --version
          sdl2-config --version
          cmake --version

      - name: Configure with SDL1
        if: matrix.sdl == 1
        run: cmake -B build -G Ninja -DSMW_OLD_STYLE_DEPS=ON -DUSE_SDL2_LIBS=OFF -DUSE_PNG_SAVE=OFF
      - name: Configure with SDL2
        if: matrix.sdl == 2
        run: cmake -B build -G Ninja -DSMW_OLD_STYLE_DEPS=ON -DUSE_SDL2_LIBS=ON -DUSE_PNG_SAVE=ON

      - name: Build
        run: cmake --build build

      - name: Package
        if: matrix.sdl == 2
        run: |
          mkdir supermariowar
          cp build/Binaries/Release/{smw,smw-leveledit,smw-worldedit,smw-server} supermariowar/
          strip supermariowar/*
          cp docs/readme-v1.8.html supermariowar/
          rsync -aC --exclude .git data supermariowar/
          zip -r "supermariowar_$(date +%F)_linux.zip" supermariowar

      - name: Upload artifacts
        if: matrix.sdl == 2
        uses: actions/upload-artifact@v3
        with:
          name: supermariowar_linux
          path: supermariowar_*_linux.zip
