name: Build - MacOS

on: [push, pull_request, workflow_dispatch]

jobs:
  macos:
    runs-on: macos-11
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'recursive'
      - name: Install dependencies
        run: brew install SDL2 SDL2_image SDL2_mixer

      - name: Configure
        run: cmake -B build -DUSE_SDL2_LIBS=ON -DUSE_PNG_SAVE=ON

      - name: Build
        run: cmake --build build

      - name: Package
        run: |
          mkdir supermariowar
          cp build/Binaries/Release/{smw,smw-leveledit,smw-worldedit,smw-server} supermariowar/
          strip supermariowar/*
          cp docs/readme-v1.8.html supermariowar/
          rsync -aC --exclude .git data supermariowar/
          zip -r "supermariowar_$(date +%F)_macos.zip" supermariowar

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: supermariowar_macos
          path: supermariowar_*_macos.zip
